version: '3.8'

services:
  redpanda:
    image: redpanda/redpanda:latest
    command: >
      redpanda start
        --overprovisioned
        --smp 1
        --memory 1G
        --reserve-memory 0M
        --node-id 0
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  redpanda_data:
