{
 "title": "Realtime-Analytics-Pipeline Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Clicks in Latest Window",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(\"count\") AS clicks_latest_window\nFROM clicks_aggregates\nWHERE window_start = (\n  SELECT MAX(window_start)\n  FROM clicks_aggregates\n);"
    }
   ]
  },
  {
   "title": "Total Clicks (10s Window)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  SUM(count) AS total_clicks\nFROM clicks_aggregates\nGROUP BY window_start\nORDER BY window_start"
    }
   ]
  },
  {
   "title": "Top 5 Pages by Click Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  page                AS page,\n  SUM(\"count\")        AS total_clicks\nFROM clicks_aggregates\nWHERE window_start\n  BETWEEN to_timestamp($__from/1000)\n      AND to_timestamp($__to/1000)\nGROUP BY page\nORDER BY total_clicks DESC\nLIMIT 5;"
    }
   ]
  }
 ]
}